// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FlagParser is an autogenerated mock type for the FlagParser type
type FlagParser struct {
	mock.Mock
}

// GetTags provides a mock function with given fields:
func (_m *FlagParser) GetTags() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewFlagParser creates a new instance of FlagParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlagParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlagParser {
	mock := &FlagParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
